path: /home/RemisAI/Bilder/Annotiert_V2 #TODO: change 
train: images/train #TODO: change
val: images/train #TODO: change

# Classes
names:
  0: Werkstueck_Scheibe
  1: Werkstueck_Zylinder
  2: Hebel
  3: Mittelkonsole
  4: Ablageflaeche
  5: Pressstueck_klein
  6: Pressstueck_gross
  7: Presstueck_mittel
  8: Raeder
  9: PresseGesamt
  
